server:
  port: 33031

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.11:10002/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  #file: newsservice.log
  file: /var/kido/logs/newsservice.log